#!/usr/bin/env python3
"""
The AI Dollar - Complete Automation
Generates videos, uploads to YouTube, posts to Instagram
Runs on schedule: 6 slots optimized for US peak hours
"""

import os
import sys
import time
import random
import threading
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
import schedule
import requests

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from video_generator import generate_daily_video, generate_long_video


PRIVACY_POLICY_HTML = b"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Privacy Policy - The AI Dollar</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.6;color:#222}
h1{font-size:24px}h2{font-size:18px;margin-top:28px}</style></head>
<body>
<h1>Privacy Policy - The AI Dollar</h1>
<p><em>Last updated: 2026</em></p>

<p>The AI Dollar ("we", "us") operates an automated content system that generates and
publishes short educational finance videos to platforms including YouTube and TikTok.
This policy explains what data our system handles.</p>

<h2>What we collect</h2>
<p>Our system does not collect, store, or process any personal data from viewers of our
videos. We do not run a website, app, or service that end users log into or submit
information to.</p>

<h2>What our system uses internally</h2>
<p>To publish content, our automated system uses API access tokens (OAuth credentials)
that we, the account owner, have authorized for our own YouTube and TikTok accounts.
These tokens are stored securely as private environment variables on our hosting
provider and are never shared with or exposed to any third party.</p>

<h2>Content we publish</h2>
<p>All video content is generated by our own automated system using publicly licensed
stock media and AI-generated scripts. No third-party personal data is used in video
production.</p>

<h2>Contact</h2>
<p>Questions about this policy can be sent via the contact details on our YouTube
channel, The AI Dollar.</p>
</body></html>"""

TERMS_OF_SERVICE_HTML = b"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Terms of Service - The AI Dollar</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.6;color:#222}
h1{font-size:24px}h2{font-size:18px;margin-top:28px}</style></head>
<body>
<h1>Terms of Service - The AI Dollar</h1>
<p><em>Last updated: 2026</em></p>

<p>The AI Dollar is an automated content system that we, its owner and operator, use
to generate and publish short educational finance videos to our own accounts on
platforms including YouTube and TikTok.</p>

<h2>Purpose</h2>
<p>This system is used solely to publish content to accounts we own and control.
It does not offer any service to the public, does not accept sign-ups, and does not
act on behalf of any third party.</p>

<h2>Content</h2>
<p>All videos are generated for general educational and entertainment purposes about
personal finance topics. They do not constitute financial, investment, tax, or legal
advice.</p>

<h2>API usage</h2>
<p>Where this system connects to third-party platform APIs (such as YouTube's or
TikTok's), it does so only to publish content to accounts we personally own and have
authorized, in compliance with each platform's developer terms.</p>

<h2>Contact</h2>
<p>Questions can be sent via the contact details on our YouTube channel, The AI Dollar.</p>
</body></html>"""


TIKTOK_VERIFICATION_FILE = "tiktokUrBsJz5EaK3QYIqFxKyGmmK9p74vdEhf.txt"
TIKTOK_VERIFICATION_CONTENT = b"tiktok-developers-site-verification=UrBsJz5EaK3QYIqFxKyGmmK9p74vdEhf"


class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        path = self.path

        if path == f"/{TIKTOK_VERIFICATION_FILE}":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(TIKTOK_VERIFICATION_CONTENT)

        elif path.startswith("/tiktok-callback"):
            import urllib.parse as _up
            query = _up.urlparse(path).query
            params = _up.parse_qs(query)
            code = params.get("code", [""])[0]
            error = params.get("error", [""])[0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            if code:
                body = (
                    f"<h1>Success</h1><p>Copy this code and paste it back into "
                    f"get_tiktok_token.py:</p><pre style='font-size:18px;background:#eee;"
                    f"padding:12px'>{code}</pre>"
                ).encode()
            else:
                body = f"<h1>Error</h1><p>{error or 'No code received'}</p>".encode()
            self.wfile.write(body)

        elif path == "/privacy":
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(PRIVACY_POLICY_HTML)

        elif path == "/terms":
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(TERMS_OF_SERVICE_HTML)

        elif path == "/test-tiktok":
            print("\n[TEST] Manual TikTok test triggered!")
            try:
                import glob
                videos = sorted(glob.glob("./videos/*.mp4"), key=os.path.getmtime, reverse=True)
                if not videos:
                    msg = b"[ERR] No video files found in ./videos yet"
                else:
                    video_path = videos[0]
                    print(f"[TEST] Using existing video: {video_path}")
                    success = upload_to_tiktok(video_path, "The AI Dollar — Personal Finance Made Simple")
                    msg = b"[OK] TikTok test posted!" if success else b"[ERR] TikTok test failed"
            except Exception as e:
                msg = f"[ERR] {str(e)}".encode()
            self.send_response(200)
            self.end_headers()
            self.wfile.write(msg)

        elif path.startswith("/media/"):
            filename = os.path.basename(path[len("/media/"):])
            filepath = os.path.join("./videos", filename)
            if filename.endswith(".mp4") and os.path.exists(filepath):
                self.send_response(200)
                self.send_header("Content-Type", "video/mp4")
                self.send_header("Content-Length", str(os.path.getsize(filepath)))
                self.end_headers()
                with open(filepath, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b"Not found")

        else:
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"The AI Dollar is running!")

    def log_message(self, format, *args):
        pass


def start_health_server():
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(("0.0.0.0", port), HealthHandler)
    print(f"[OK] Health server running on port {port}")
    server.serve_forever()


def upload_to_youtube(video_path, title, description, is_short=True, keywords=None, thumbnail_path=None):
    """Upload video to YouTube using OAuth refresh token"""
    try:
        refresh_token = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
        if not refresh_token:
            print("[WARN] YOUTUBE_REFRESH_TOKEN not set -- skipping YouTube")
            return False

        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
        from googleapiclient.errors import HttpError

        CLIENT_ID     = os.getenv("YOUTUBE_CLIENT_ID", "")
        CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
        if not CLIENT_ID or not CLIENT_SECRET:
            print("[WARN] YOUTUBE_CLIENT_ID or YOUTUBE_CLIENT_SECRET not set -- skipping YouTube")
            return False

        creds = Credentials(
            token=None,
            refresh_token=refresh_token,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=CLIENT_ID,
            client_secret=CLIENT_SECRET,
            scopes=["https://www.googleapis.com/auth/youtube.upload"]
        )

        youtube = build("youtube", "v3", credentials=creds)

        topic_tags = keywords if keywords else []
        base_tags = [
            "personal finance", "money tips", "investing for beginners",
            "financial literacy", "how to invest", "money management",
            "wealth building", "passive income", "financial education",
            "stock market for beginners", "save money", "make money online",
            "budget tips", "debt free journey", "credit score tips",
            "side hustle ideas 2026", "financial freedom", "money advice",
            "finance tips", "how to get rich", "TheAIDollar",
            "money hacks that work", "rich vs poor habits", "compound interest explained",
            "index funds for beginners", "roth ira explained", "how to save money fast",
            "money mistakes to avoid", "millionaire habits", "financial independence",
            "how to build wealth", "money rules", "investing tips 2026",
        ]
        yt_tags = topic_tags + [t for t in base_tags if t.lower() not in [k.lower() for k in topic_tags]]
        import re
        yt_tags = [re.sub(r'[<>",]', '', t).strip() for t in yt_tags if t.strip()]
        yt_tags = [t[:30] for t in yt_tags if t]
        total = 0
        trimmed = []
        for t in yt_tags:
            added = len(t) + (1 if trimmed else 0)
            if total + added > 450:
                break
            trimmed.append(t)
            total += added
        yt_tags = trimmed

        kw_line = ", ".join(topic_tags[:5]) if topic_tags else "money tips, finance, investing"

        if is_short:
            yt_title = title[:100]
            hooks = [
                "This changes everything about how you think about money.",
                "99% of people don't know this. Now you do.",
                "Watch this before you spend another dollar.",
                "This is the money lesson schools refuse to teach.",
                "If you're broke, this video is your wake-up call.",
                "I wish someone told me this at 18.",
                "This is why most people stay broke forever.",
                "The money truth nobody wants to hear.",
                "Stop what you're doing and watch this.",
                "The financial advice that actually works in 2026.",
                "Most financial gurus won't tell you this for free.",
                "This one money move changed everything for me.",
            ]
            open_loops = [
                "The last tip is the one that changes everything.",
                "Wait for the final part — it's worth 10x the rest.",
                "Tip #3 alone is worth watching the whole video.",
                "The ending will shock you.",
            ]
            yt_desc = (
                f"{kw_line} — {title}\n"
                f"Learn {kw_line} in 60 seconds. Free finance education daily.\n\n"
                f"{random.choice(hooks)}\n"
                f"{random.choice(open_loops)}\n\n"
                f"WATCH MORE:\n"
                f"Subscribe for daily money lessons: https://www.youtube.com/@TheAIDollar?sub_confirmation=1\n\n"
                f"ENGAGE:\n"
                f"Comment your #1 money struggle below\n"
                f"Share this with someone who needs to hear it\n"
                f"Turn on notifications — new videos every day\n\n"
                f"TOPICS COVERED: {kw_line}, personal finance tips, "
                f"how to build wealth, money management for beginners, "
                f"investing basics, financial literacy 2026\n\n"
                f"#Shorts #Finance #Money #Investing #PersonalFinance "
                f"#WealthBuilding #FinancialFreedom #MoneyTips "
                f"#HowToGetRich #PassiveIncome #DebtFree #SideHustle "
                f"#FinancialLiteracy #MakeMoney #MoneyHacks "
                f"#InvestingForBeginners #TheAIDollar "
                f"#MillionaireMindset #FinancialEducation "
                f"#MoneyTok #FinTok #LearnOnYouTube"
            )
            yt_tags.append("Shorts")
        else:
            yt_title = title[:100]
            intros = [
                f"Most people will scroll past this. But if you watch to the end, you'll know more about {kw_line} than 99% of people.",
                f"This is the complete breakdown of {kw_line} that nobody else is giving you for free.",
                f"Everything you need to know about {kw_line} in one video. No fluff. No BS. Just actionable steps.",
                f"I spent hours researching {kw_line} so you don't have to. Here's everything that actually matters.",
                f"This {kw_line} guide is what I wish I had when I started. Watch it twice.",
                f"WARNING: Once you learn this about {kw_line}, you can't unlearn it.",
            ]
            yt_desc = (
                f"{kw_line} — {title} | The AI Dollar\n"
                f"Learn {kw_line}, personal finance tips, and wealth-building strategies. "
                f"Free financial education for beginners and beyond.\n\n"
                f"{random.choice(intros)}\n\n"
                f"TIMESTAMPS:\n"
                f"0:00 - Introduction — why {kw_line} matters\n"
                f"0:45 - The core concept explained simply\n"
                f"2:00 - Real-world examples and proof\n"
                f"4:00 - Step-by-step action plan you can start TODAY\n"
                f"6:00 - Common mistakes that keep people broke\n"
                f"8:00 - The #1 thing to do RIGHT NOW\n\n"
                f"WHAT YOU'LL LEARN:\n"
                f"- How {kw_line} actually works in real life\n"
                f"- The biggest mistakes beginners make\n"
                f"- A step-by-step action plan anyone can follow\n"
                f"- Why starting TODAY beats waiting for 'the right time'\n\n"
                f"FREE RESOURCES:\n"
                f"- High yield savings: Most online banks offer 4-5% APY\n"
                f"- Index fund investing: Fidelity, Vanguard, Schwab (zero minimums)\n"
                f"- Budget tracking: Free apps like Mint or YNAB trial\n\n"
                f"If this helped you, do these 3 things:\n"
                f"1. SUBSCRIBE and turn on ALL notifications\n"
                f"2. COMMENT your biggest takeaway below\n"
                f"3. SHARE with someone who needs to hear this\n\n"
                f"We post 4 videos EVERY DAY — shorts + deep dives.\n"
                f"New here? Start with our most popular videos on the channel page.\n\n"
                f"RELATED TOPICS: {kw_line}, personal finance for beginners, "
                f"how to invest money, budgeting tips, wealth building strategies, "
                f"financial literacy 2026, money management, passive income ideas\n\n"
                f"Subscribe: https://www.youtube.com/@TheAIDollar?sub_confirmation=1\n\n"
                f"#Finance #Money #PersonalFinance #Investing #WealthBuilding "
                f"#FinancialFreedom #MoneyTips #FinancialLiteracy "
                f"#HowToGetRich #StockMarket #PassiveIncome #DebtFree "
                f"#InvestingForBeginners #TheAIDollar "
                f"#MillionaireMindset #FinancialEducation "
                f"#MoneyMindset #WealthSecrets"
            )

        print(f"[TAGS] {len(yt_tags)} tags, {len(','.join(yt_tags))} chars: {yt_tags}")

        def _upload(tags):
            body = {
                "snippet": {
                    "title": yt_title,
                    "description": yt_desc,
                    "tags": tags,
                    "categoryId": "22",
                },
                "status": {
                    "privacyStatus": "public",
                    "selfDeclaredMadeForKids": False,
                },
            }
            media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
            request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    print(f"[UPLOAD] YouTube: {int(status.progress() * 100)}% uploaded")
            return response

        try:
            response = _upload(yt_tags)
        except HttpError as e:
            if "invalidTags" in str(e) or "invalid video keywords" in str(e):
                print(f"[WARN] Tags rejected ({e}), retrying with minimal safe tags...")
                safe_tags = ["personal finance", "money tips", "investing", "financial education", "TheAIDollar"]
                try:
                    response = _upload(safe_tags)
                except HttpError as e2:
                    print(f"[WARN] Minimal tags also rejected ({e2}), retrying with no tags...")
                    response = _upload([])
            else:
                raise

        video_id = response.get("id", "")
        print(f"[OK] YouTube uploaded! https://youtube.com/watch?v={video_id}")

        if thumbnail_path and os.path.exists(thumbnail_path) and video_id:
            try:
                youtube.thumbnails().set(
                    videoId=video_id,
                    media_body=MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
                ).execute()
                print(f"[OK] Custom thumbnail set for {video_id}")
            except Exception as te:
                print(f"[WARN] Thumbnail upload failed (requires verified channel): {te}")

        return True

    except Exception as e:
        print(f"[ERR] YouTube error: {e}")
        import traceback
        traceback.print_exc()
        return False


PUBLIC_BASE_URL = "https://the-ai-dollar.onrender.com"


def upload_to_instagram(video_path, title, keywords=None):
    """Post to Instagram via a Make.com scenario instead of talking to Meta
    directly — Make.com already has verified Meta API access, so this
    sidesteps Meta Developer Portal's SMS verification step entirely.
    Sends a webhook with a public URL to the video (Make's Instagram
    module fetches it from there) plus the caption."""
    webhook_url = os.getenv("MAKE_INSTAGRAM_WEBHOOK_URL", "")
    if not webhook_url:
        print("[SKIP] Instagram: MAKE_INSTAGRAM_WEBHOOK_URL not set")
        return False

    try:
        # SEO: lead with the title (already keyword-rich — it names both
        # confusable terms verbatim, which is what people actually search).
        # Keep hashtags small and targeted instead of a 15-tag wall — Meta's
        # own creator guidance says a spammy-looking tag block suppresses
        # reach rather than helping discovery.
        kw_list = [k for k in (keywords or []) if k and len(k) <= 30][:5]
        kw_tags = " ".join(f"#{k.replace(' ', '').replace('-', '')}" for k in kw_list)
        broad_tags = "#PersonalFinance #MoneyTips #FinancialLiteracy"

        ig_hooks = [
            "Save this for later.",
            "Share this with someone who needs it.",
            "Tag a friend who needs to hear this.",
            "Double tap if you agree.",
        ]
        caption = (
            f"{title}\n\n"
            f"{random.choice(ig_hooks)}\n\n"
            f"Follow @theaidollar for daily money tips that actually work.\n\n"
            f"{broad_tags} {kw_tags} #Reels"
        )

        video_url = f"{PUBLIC_BASE_URL}/media/{os.path.basename(video_path)}"
        print(f"[Instagram] Notifying Make.com: {video_url}")

        resp = requests.post(
            webhook_url,
            json={"video_url": video_url, "caption": caption, "title": title},
            timeout=20,
        )
        if resp.status_code not in (200, 201, 202):
            print(f"[ERR] Instagram webhook failed: {resp.status_code} - {resp.text[:200]}")
            return False

        print("[OK] Instagram: sent to Make.com for posting")
        return True

    except Exception as e:
        print(f"[ERR] Instagram error: {e}")
        return False


def upload_to_facebook(video_path, title, keywords=None):
    """Upload video to Facebook Page as Reel"""
    page_token = os.getenv("FACEBOOK_PAGE_TOKEN", "")
    page_id = os.getenv("FACEBOOK_PAGE_ID", "")
    if not page_token or not page_id:
        print("[SKIP] Facebook: FACEBOOK_PAGE_TOKEN or FACEBOOK_PAGE_ID not set")
        return False

    try:
        kw_tags = " ".join(f"#{k.replace(' ', '')}" for k in (keywords or [])[:5])
        description = (
            f"{title}\n\n"
            f"Like + Follow The AI Dollar for daily money education.\n"
            f"New shorts and deep dives every day.\n\n"
            f"#Finance #Money #PersonalFinance #Investing "
            f"#FinanceTips #WealthBuilding #FinancialLiteracy "
            f"#MoneyHacks #FinancialFreedom #DebtFree "
            f"#InvestingForBeginners #MoneyTips {kw_tags}"
        )

        print("[UPLOAD] Facebook: uploading reel...")
        init_url = f"https://graph.facebook.com/v18.0/{page_id}/video_reels"
        init_resp = requests.post(init_url, data={
            "upload_phase": "start",
            "access_token": page_token,
        })
        if init_resp.status_code != 200:
            print(f"[ERR] Facebook init failed: {init_resp.text}")
            return False

        video_id = init_resp.json().get("video_id")

        upload_url = f"https://rupload.facebook.com/video-upload/v18.0/{video_id}"
        file_size = os.path.getsize(video_path)
        with open(video_path, "rb") as f:
            upload_resp = requests.post(upload_url, data=f, headers={
                "Authorization": f"OAuth {page_token}",
                "offset": "0",
                "file_size": str(file_size),
                "Content-Type": "application/octet-stream",
            })
        if upload_resp.status_code != 200:
            print(f"[ERR] Facebook upload failed: {upload_resp.text}")
            return False

        publish_resp = requests.post(init_url, data={
            "upload_phase": "finish",
            "access_token": page_token,
            "video_id": video_id,
            "title": title[:100],
            "description": description,
        })
        if publish_resp.status_code == 200:
            print(f"[OK] Facebook Reel posted! Video ID: {video_id}")
            return True
        else:
            print(f"[ERR] Facebook publish failed: {publish_resp.text}")
            return False

    except Exception as e:
        print(f"[ERR] Facebook error: {e}")
        return False


def post_video(is_series_part=False, series_name="", part_num=0, post_instagram=True):
    """Generate and post video to YouTube + TikTok (+ Instagram when
    post_instagram=True). Instagram Reels reach is hurt by over-posting —
    Meta's own creator guidance caps effective frequency around 1-2/day,
    unlike YouTube Shorts/TikTok which reward higher volume — so only a
    couple of the day's scheduled slots pass post_instagram=True."""
    print(f"\n{'='*50}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] POSTING VIDEO{' [SERIES PART]' if is_series_part else ''}")
    print(f"{'='*50}\n")

    try:
        print("[STEP 1] Generating video...")
        result = generate_daily_video()

        if result['status'] != 'success':
            print(f"[ERR] Video generation failed: {result.get('message','')}")
            return

        video_path = result['video']
        title      = result['title']
        script     = result['script']
        keywords   = result.get('keywords', [])
        print(f"[OK] Video generated: {title}")

        print(f"\n[STEP 2] Uploading to YouTube...")
        youtube_success = upload_to_youtube(video_path, title, script, is_short=True, keywords=keywords)

        print(f"\n[STEP 3] Uploading to TikTok...")
        tiktok_success = upload_to_tiktok(video_path, title, keywords=keywords)

        if post_instagram:
            print(f"\n[STEP 4] Uploading to Instagram...")
            instagram_success = upload_to_instagram(video_path, title, keywords=keywords)
        else:
            print(f"\n[STEP 4] Skipping Instagram this slot (throttled to ~2 posts/day for reach)")
            instagram_success = None

        with open("last_post_time.txt", "w") as f:
            f.write(str(time.time()))

        print(f"\n{'='*50}")
        print(f"[DONE] POSTING COMPLETE")
        print(f"   YouTube:   {'posted' if youtube_success else 'FAILED'}")
        print(f"   TikTok:    {'posted' if tiktok_success else 'FAILED'}")
        ig_status = "skipped (throttled)" if instagram_success is None else ("posted" if instagram_success else "FAILED")
        print(f"   Instagram: {ig_status}")
        print(f"{'='*50}\n")

    except Exception as e:
        print(f"[ERR] Error in post_video: {e}")
        import traceback
        traceback.print_exc()


def post_long_video():
    """Generate and post a long-form video to YouTube + TikTok"""
    print(f"\n{'='*50}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] POSTING LONG-FORM VIDEO")
    print(f"{'='*50}\n")

    try:
        print("[STEP 1] Generating long-form video...")
        result = generate_long_video()

        if result['status'] != 'success':
            print(f"[ERR] Long video generation failed: {result.get('message','')}")
            return

        video_path = result['video']
        title      = result['title']
        script     = result['script']
        keywords   = result.get('keywords', [])
        thumb      = result.get('thumbnail')
        print(f"[OK] Long video generated: {title}")

        print(f"\n[STEP 2] Uploading to YouTube (long-form)...")
        youtube_success = upload_to_youtube(video_path, title, script, is_short=False, keywords=keywords, thumbnail_path=thumb)

        print(f"\n[STEP 3] Uploading to TikTok...")
        tiktok_success = upload_to_tiktok(video_path, title, keywords=keywords)

        with open("last_post_time.txt", "w") as f:
            f.write(str(time.time()))

        print(f"\n{'='*50}")
        print(f"[DONE] LONG-FORM POSTING COMPLETE")
        print(f"   YouTube:   {'posted' if youtube_success else 'FAILED'}")
        print(f"   TikTok:    {'posted' if tiktok_success else 'FAILED'}")
        print(f"{'='*50}\n")

    except Exception as e:
        print(f"[ERR] Error in post_long_video: {e}")
        import traceback
        traceback.print_exc()


def keep_alive():
    """Self-ping to prevent Render free tier from spinning down"""
    try:
        requests.get("https://the-ai-dollar.onrender.com/", timeout=10)
    except Exception:
        pass


def upload_to_tiktok(video_path, title, keywords=None):
    """Upload video to TikTok using the official Content Posting API."""
    client_key = os.getenv("TIKTOK_CLIENT_KEY", "").strip()
    client_secret = os.getenv("TIKTOK_CLIENT_SECRET", "").strip()
    refresh_token = os.getenv("TIKTOK_REFRESH_TOKEN", "").strip()

    if not client_key or not client_secret or not refresh_token:
        print("[SKIP] TikTok: TIKTOK_CLIENT_KEY/CLIENT_SECRET/REFRESH_TOKEN not fully set")
        return False

    print(f"[TikTok] client_key len={len(client_key)} repr={client_key[:4]!r}...{client_key[-4:]!r}")
    print(f"[TikTok] client_secret len={len(client_secret)}")
    print(f"[TikTok] refresh_token len={len(refresh_token)} repr={refresh_token[:8]!r}...{refresh_token[-8:]!r}")

    try:
        import requests as req

        kw_tags = " ".join(f"#{k.replace(' ', '')}" for k in (keywords or [])[:3])
        caption = (
            f"{title[:60]} "
            f"#moneytok #fintok #investing #finance #personalfinance "
            f"#moneytips #financialfreedom #wealthbuilding "
            f"#learnontiktok #fyp #viral {kw_tags}"
        )[:150]

        print("[TikTok] Refreshing access token...")
        token_resp = req.post(
            "https://open.tiktokapis.com/v2/oauth/token/",
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            data={
                "client_key": client_key,
                "client_secret": client_secret,
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            },
            timeout=20,
        )
        token_data = token_resp.json()
        access_token = token_data.get("access_token")
        if not access_token:
            print(f"[ERR] TikTok token refresh failed: {token_data}")
            return False

        auth_headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json; charset=UTF-8",
        }

        print("[TikTok] Querying creator info...")
        creator_resp = req.post(
            "https://open.tiktokapis.com/v2/post/publish/creator_info/query/",
            headers=auth_headers,
            timeout=20,
        )
        creator_data = creator_resp.json().get("data", {})
        privacy_options = creator_data.get("privacy_level_options", ["SELF_ONLY"])

        # Unaudited apps can ONLY post as SELF_ONLY, even if PUBLIC_TO_EVERYONE
        # is listed as an option — TikTok's posting endpoint enforces this
        # separately from what creator_info reports. Flip TIKTOK_AUDITED=true
        # on Render once the app passes review to allow public posting.
        if os.getenv("TIKTOK_AUDITED", "false").lower() == "true" and "PUBLIC_TO_EVERYONE" in privacy_options:
            privacy_level = "PUBLIC_TO_EVERYONE"
        else:
            privacy_level = "SELF_ONLY"
        print(f"[TikTok] Privacy level: {privacy_level}")

        file_size = os.path.getsize(video_path)
        print(f"[TikTok] Video size: {file_size / 1024 / 1024:.1f}MB")

        print("[TikTok] Initializing post...")
        init_resp = req.post(
            "https://open.tiktokapis.com/v2/post/publish/video/init/",
            headers=auth_headers,
            json={
                "post_info": {
                    "title": caption,
                    "privacy_level": privacy_level,
                    "disable_duet": False,
                    "disable_comment": False,
                    "disable_stitch": False,
                    "video_cover_timestamp_ms": 1000,
                },
                "source_info": {
                    "source": "FILE_UPLOAD",
                    "video_size": file_size,
                    "chunk_size": file_size,
                    "total_chunk_count": 1,
                },
            },
            timeout=20,
        )
        init_data = init_resp.json()
        if "data" not in init_data or "publish_id" not in init_data["data"]:
            print(f"[ERR] TikTok init failed: {init_data}")
            return False

        publish_id = init_data["data"]["publish_id"]
        upload_url = init_data["data"]["upload_url"]

        print("[TikTok] Uploading video...")
        with open(video_path, 'rb') as f:
            video_data = f.read()

        upload_resp = req.put(
            upload_url,
            headers={
                "Content-Type": "video/mp4",
                "Content-Range": f"bytes 0-{file_size - 1}/{file_size}",
            },
            data=video_data,
            timeout=120,
        )
        print(f"[TikTok] Upload response: {upload_resp.status_code}")
        if upload_resp.status_code not in (200, 201):
            print(f"[ERR] TikTok upload failed: {upload_resp.status_code} - {upload_resp.text[:200]}")
            return False

        print("[TikTok] Checking publish status...")
        for _ in range(6):
            time.sleep(5)
            status_resp = req.post(
                "https://open.tiktokapis.com/v2/post/publish/status/fetch/",
                headers=auth_headers,
                json={"publish_id": publish_id},
                timeout=20,
            )
            status_data = status_resp.json().get("data", {})
            status = status_data.get("status")
            print(f"[TikTok] Status: {status}")
            if status == "PUBLISH_COMPLETE":
                print(f"[OK] TikTok posted! Title: {title[:50]}")
                return True
            if status == "FAILED":
                print(f"[ERR] TikTok publish failed: {status_data}")
                return False

        print("[WARN] TikTok publish status unknown after polling, treating as posted")
        return True

    except Exception as e:
        print(f"[ERR] TikTok error: {e}")
        return False


def schedule_jobs():
    # SHORTS ONLY — discovery engine for small channels
    # Shorts get shown on the Shorts shelf to non-subscribers
    # 6 per day, spaced across US peak SCROLLING windows (times in UTC, EDT = UTC-4)
    # Replaced the old 2am EDT slot (dead time) with a second prime-time slot.
    # Instagram Reels reach drops off with over-posting (Meta's own creator
    # guidance points to ~1-2/day), unlike YouTube Shorts/TikTok which
    # reward volume — so only the two strongest windows (lunch + prime
    # time) also go to Instagram; the rest post YouTube + TikTok only.
    schedule.every().day.at("11:00").do(post_video, post_instagram=False)  # US East 7am — wake up / commute scroll
    schedule.every().day.at("15:30").do(post_video, post_instagram=True)   # US East 11:30am — lunch break
    schedule.every().day.at("18:00").do(post_video, post_instagram=False)  # US East 2pm — afternoon slump scroll
    schedule.every().day.at("21:00").do(post_video, post_instagram=False)  # US East 5pm — evening commute
    schedule.every().day.at("23:30").do(post_video, post_instagram=True)   # US East 7:30pm — prime time
    schedule.every().day.at("01:30").do(post_video, post_instagram=False)  # US East 9:30pm — late-night scroll (peak Shorts engagement)

    schedule.every(10).minutes.do(keep_alive)
    print("[OK] Schedule: 6 Shorts/day on YouTube+TikTok, 2/day on Instagram (growth mode)")
    print("[OK] Shorts = discovery engine for non-subscribers")
    print("[OK] Self-ping every 10 min to prevent Render spin-down")


def main():
    print("\n[START] THE AI DOLLAR - AUTOMATION STARTED")
    print("=" * 50)
    print(f"Started at: {datetime.now()}")
    print("=" * 50)

    health_thread = threading.Thread(target=start_health_server, daemon=True)
    health_thread.start()

    schedule_jobs()

    print("\n[NOW] Posting first short on startup...\n")
    try:
        post_video()
    except Exception as e:
        print(f"[ERR] Startup post error: {e}")

    print("\n[SCHED] Scheduler running (6 shorts/day — growth mode + self-ping every 10 min)...")
    try:
        while True:
            schedule.run_pending()
            time.sleep(60)
    except KeyboardInterrupt:
        print("\n[STOP] Stopped")


if __name__ == "__main__":
    main()
