#!/usr/bin/env python3
"""
The AI Dollar - Complete Automation
Generates videos, uploads to YouTube, posts to Instagram
Runs on schedule: 6 slots optimized for US peak hours
"""

import os
import sys
import time
import random
import threading
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
import schedule
import requests

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from video_generator import generate_daily_video, generate_long_video


PRIVACY_POLICY_HTML = b"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Privacy Policy - The AI Dollar</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.6;color:#222}
h1{font-size:24px}h2{font-size:18px;margin-top:28px}</style></head>
<body>
<h1>Privacy Policy - The AI Dollar</h1>
<p><em>Last updated: 2026</em></p>

<p>The AI Dollar ("we", "us") operates an automated content system that generates and
publishes short educational finance videos to platforms including YouTube and TikTok.
This policy explains what data our system handles.</p>

<h2>What we collect</h2>
<p>Our system does not collect, store, or process any personal data from viewers of our
videos. We do not run a website, app, or service that end users log into or submit
information to.</p>

<h2>What our system uses internally</h2>
<p>To publish content, our automated system uses API access tokens (OAuth credentials)
that we, the account owner, have authorized for our own YouTube and TikTok accounts.
These tokens are stored securely as private environment variables on our hosting
provider and are never shared with or exposed to any third party.</p>

<h2>Content we publish</h2>
<p>All video content is generated by our own automated system using publicly licensed
stock media and AI-generated scripts. No third-party personal data is used in video
production.</p>

<h2>Contact</h2>
<p>Questions about this policy can be sent via the contact details on our YouTube
channel, The AI Dollar.</p>
</body></html>"""

TERMS_OF_SERVICE_HTML = b"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Terms of Service - The AI Dollar</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.6;color:#222}
h1{font-size:24px}h2{font-size:18px;margin-top:28px}</style></head>
<body>
<h1>Terms of Service - The AI Dollar</h1>
<p><em>Last updated: 2026</em></p>

<p>The AI Dollar is an automated content system that we, its owner and operator, use
to generate and publish short educational finance videos to our own accounts on
platforms including YouTube and TikTok.</p>

<h2>Purpose</h2>
<p>This system is used solely to publish content to accounts we own and control.
It does not offer any service to the public, does not accept sign-ups, and does not
act on behalf of any third party.</p>

<h2>Content</h2>
<p>All videos are generated for general educational and entertainment purposes about
personal finance topics. They do not constitute financial, investment, tax, or legal
advice.</p>

<h2>API usage</h2>
<p>Where this system connects to third-party platform APIs (such as YouTube's or
TikTok's), it does so only to publish content to accounts we personally own and have
authorized, in compliance with each platform's developer terms.</p>

<h2>Contact</h2>
<p>Questions can be sent via the contact details on our YouTube channel, The AI Dollar.</p>
</body></html>"""


TIKTOK_VERIFICATION_FILE = "tiktokUrBsJz5EaK3QYIqFxKyGmmK9p74vdEhf.txt"
TIKTOK_VERIFICATION_CONTENT = b"tiktok-developers-site-verification=UrBsJz5EaK3QYIqFxKyGmmK9p74vdEhf"


class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        path = self.path

        if path == f"/{TIKTOK_VERIFICATION_FILE}":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(TIKTOK_VERIFICATION_CONTENT)

        elif path.startswith("/tiktok-callback"):
            import urllib.parse as _up
            query = _up.urlparse(path).query
            params = _up.parse_qs(query)
            code = params.get("code", [""])[0]
            error = params.get("error", [""])[0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            if code:
                body = (
                    f"<h1>Success</h1><p>Copy this code and paste it back into "
                    f"get_tiktok_token.py:</p><pre style='font-size:18px;background:#eee;"
                    f"padding:12px'>{code}</pre>"
                ).encode()
            else:
                body = f"<h1>Error</h1><p>{error or 'No code received'}</p>".encode()
            self.wfile.write(body)

        elif path == "/privacy":
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(PRIVACY_POLICY_HTML)

        elif path == "/terms":
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(TERMS_OF_SERVICE_HTML)

        elif path == "/test-tiktok":
            print("\n[TEST] Manual TikTok test triggered!")
            try:
                import glob
                videos = sorted(glob.glob("./videos/*.mp4"), key=os.path.getmtime, reverse=True)
                if not videos:
                    msg = b"[ERR] No video files found in ./videos yet"
                else:
                    video_path = videos[0]
                    print(f"[TEST] Using existing video: {video_path}")
                    success = upload_to_tiktok(video_path, "The AI Dollar — Personal Finance Made Simple")
                    msg = b"[OK] TikTok test posted!" if success else b"[ERR] TikTok test failed"
            except Exception as e:
                msg = f"[ERR] {str(e)}".encode()
            self.send_response(200)
            self.end_headers()
            self.wfile.write(msg)

        elif path.startswith("/media/"):
            filename = os.path.basename(path[len("/media/"):])
            filepath = os.path.join("./videos", filename)
            if filename.endswith(".mp4") and os.path.exists(filepath):
                self.send_response(200)
                self.send_header("Content-Type", "video/mp4")
                self.send_header("Content-Length", str(os.path.getsize(filepath)))
                self.end_headers()
                with open(filepath, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b"Not found")

        elif path == "/status":
            import json as _json
            last_post = "never"
            try:
                if os.path.exists("last_post_time.txt"):
                    with open("last_post_time.txt") as _f:
                        ts = float(_f.read().strip())
                        last_post = datetime.utcfromtimestamp(ts).strftime("%Y-%m-%d %H:%M UTC")
            except Exception:
                pass
            status = {
                "server_time_utc": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "PAUSE_POSTING": os.getenv("PAUSE_POSTING", "(not set)"),
                "posting_active": os.getenv("PAUSE_POSTING", "false").lower() != "true",
                "INSTAGRAM_RESUME_DATE": os.getenv("INSTAGRAM_RESUME_DATE", "(not set)"),
                "FISH_AUDIO_API_KEY_set": bool(os.getenv("FISH_AUDIO_API_KEY")),
                "MAKE_INSTAGRAM_WEBHOOK_set": bool(os.getenv("MAKE_INSTAGRAM_WEBHOOK_URL")),
                "GEMINI_API_KEY_set": bool(os.getenv("GEMINI_API_KEY")),
                "YOUTUBE_REFRESH_TOKEN_set": bool(os.getenv("YOUTUBE_REFRESH_TOKEN")),
                "last_post": last_post,
                "current_run": _LAST_RUN,
                "schedule_utc": ["15:30 Instagram", "20:00 YouTube+Instagram"],
                "tiktok": "off until TIKTOK_AUDITED=true (app not approved)",
            }
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(_json.dumps(status, indent=2).encode())

        elif path == "/post-now":
            # Manual on-demand post to ALL platforms (ignores PAUSE_POSTING and
            # the Instagram schedule) so the full chain can be tested instantly.
            print("\n[MANUAL] /post-now triggered — posting to all platforms")
            threading.Thread(
                target=lambda: post_video(post_instagram=True, force=True),
                daemon=True,
            ).start()
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"Posting started (all platforms). Check logs / your accounts in ~3-5 min.")

        else:
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"The AI Dollar is running!")

    def log_message(self, format, *args):
        pass


def start_health_server():
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(("0.0.0.0", port), HealthHandler)
    print(f"[OK] Health server running on port {port}")
    server.serve_forever()


def upload_to_youtube(video_path, title, description, is_short=True, keywords=None, thumbnail_path=None):
    """Upload video to YouTube using OAuth refresh token"""
    try:
        refresh_token = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
        if not refresh_token:
            print("[WARN] YOUTUBE_REFRESH_TOKEN not set -- skipping YouTube")
            return False

        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
        from googleapiclient.errors import HttpError

        CLIENT_ID     = os.getenv("YOUTUBE_CLIENT_ID", "")
        CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
        if not CLIENT_ID or not CLIENT_SECRET:
            print("[WARN] YOUTUBE_CLIENT_ID or YOUTUBE_CLIENT_SECRET not set -- skipping YouTube")
            return False

        creds = Credentials(
            token=None,
            refresh_token=refresh_token,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=CLIENT_ID,
            client_secret=CLIENT_SECRET,
            scopes=["https://www.googleapis.com/auth/youtube.upload"]
        )

        youtube = build("youtube", "v3", credentials=creds)

        # TAGS — deliberately few and specific. Stuffing 30+ generic tags is
        # a soft negative ranking signal on YouTube now; current guidance is
        # ~3-5 focused tags: the exact topic, close variants, then one or two
        # broader category tags. Topic keywords come from the AI script, so
        # they're the real subject of THIS video rather than boilerplate.
        import re
        topic_tags = [k for k in (keywords or []) if k and k.strip()][:4]
        broad_tags = ["personal finance", "financial literacy"]
        yt_tags = topic_tags + [t for t in broad_tags
                                if t.lower() not in [k.lower() for k in topic_tags]]
        yt_tags = [re.sub(r'[<>",]', '', t).strip()[:30] for t in yt_tags]
        yt_tags = [t for t in yt_tags if t][:6]

        kw_line = ", ".join(topic_tags[:3]) if topic_tags else "money tips, finance, investing"
        primary_kw = topic_tags[0] if topic_tags else "personal finance"

        if is_short:
            yt_title = title[:100]
            hooks = [
                "This changes everything about how you think about money.",
                "99% of people don't know this. Now you do.",
                "Watch this before you spend another dollar.",
                "This is the money lesson schools refuse to teach.",
                "If you're broke, this video is your wake-up call.",
                "I wish someone told me this at 18.",
                "This is why most people stay broke forever.",
                "The money truth nobody wants to hear.",
                "Stop what you're doing and watch this.",
                "The financial advice that actually works in 2026.",
                "Most financial gurus won't tell you this for free.",
                "This one money move changed everything for me.",
            ]
            open_loops = [
                "The last tip is the one that changes everything.",
                "Wait for the final part — it's worth 10x the rest.",
                "Tip #3 alone is worth watching the whole video.",
                "The ending will shock you.",
            ]
            # DESCRIPTION — leads with the real topic keyword inside the
            # first ~100 characters (what YouTube reads to classify a Short),
            # then natural prose.
            #
            # HASHTAGS — 7, mixing the recommended layers: platform tag,
            # niche tags, and one specific to this video. Deliberately
            # EXCLUDED after reviewing what competing finance Shorts use:
            #   #finance / #money   - hundreds of millions of posts; a small
            #                         channel is buried instantly
            #   #makemoneyonline    - get-rich-quick intent, wrong audience
            #   #sidehustles        - we don't cover side hustles
            #   #passiveincome      - wrong topic, attracts the wrong viewer
            #   #moneymindset       - vague motivational, not educational
            #   #stockmarketshorts  - we don't do stock picking
            #   #crypto2025         - stale year tag, off-topic
            # Keep the keyword's own casing — .title() would turn an acronym
            # like "APR vs APY" into the unreadable "#AprVsApy".
            hashtag_kw = re.sub(r'[^A-Za-z0-9]', '', primary_kw) or "PersonalFinance"
            yt_hashtags = " ".join([
                "#Shorts",                 # platform tag: required for the Shorts feed
                f"#{hashtag_kw}",          # this video's exact topic
                "#PersonalFinance",        # core niche
                "#FinancialLiteracy",      # matches "explaining terms" intent
                "#MoneyTips",              # medium-competition, on-topic
                "#FinanceShorts",          # niche + format, less saturated
                "#FinanceForBeginners",    # matches our actual audience
            ])
            yt_desc = (
                f"{title}\n\n"
                f"{primary_kw} explained in under a minute — the difference "
                f"most people get wrong, in plain English with a real example.\n\n"
                f"{random.choice(hooks)} {random.choice(open_loops)}\n\n"
                f"This channel breaks down one confusing pair of money terms "
                f"every day: what each one actually means, how to tell them "
                f"apart in seconds, and what mixing them up costs you in real "
                f"dollars. No jargon, no filler.\n\n"
                f"Covered here: {kw_line}.\n\n"
                f"Comment which one you always mixed up, and subscribe for a "
                f"new money term explained daily:\n"
                f"https://www.youtube.com/@TheAIDollar?sub_confirmation=1\n\n"
                f"{yt_hashtags}"
            )
            yt_tags.append("Shorts")
        else:
            yt_title = title[:100]
            intros = [
                f"Most people will scroll past this. But if you watch to the end, you'll know more about {kw_line} than 99% of people.",
                f"This is the complete breakdown of {kw_line} that nobody else is giving you for free.",
                f"Everything you need to know about {kw_line} in one video. No fluff. No BS. Just actionable steps.",
                f"I spent hours researching {kw_line} so you don't have to. Here's everything that actually matters.",
                f"This {kw_line} guide is what I wish I had when I started. Watch it twice.",
                f"WARNING: Once you learn this about {kw_line}, you can't unlearn it.",
            ]
            yt_desc = (
                f"{kw_line} — {title} | The AI Dollar\n"
                f"Learn {kw_line}, personal finance tips, and wealth-building strategies. "
                f"Free financial education for beginners and beyond.\n\n"
                f"{random.choice(intros)}\n\n"
                f"TIMESTAMPS:\n"
                f"0:00 - Introduction — why {kw_line} matters\n"
                f"0:45 - The core concept explained simply\n"
                f"2:00 - Real-world examples and proof\n"
                f"4:00 - Step-by-step action plan you can start TODAY\n"
                f"6:00 - Common mistakes that keep people broke\n"
                f"8:00 - The #1 thing to do RIGHT NOW\n\n"
                f"WHAT YOU'LL LEARN:\n"
                f"- How {kw_line} actually works in real life\n"
                f"- The biggest mistakes beginners make\n"
                f"- A step-by-step action plan anyone can follow\n"
                f"- Why starting TODAY beats waiting for 'the right time'\n\n"
                f"FREE RESOURCES:\n"
                f"- High yield savings: Most online banks offer 4-5% APY\n"
                f"- Index fund investing: Fidelity, Vanguard, Schwab (zero minimums)\n"
                f"- Budget tracking: Free apps like Mint or YNAB trial\n\n"
                f"If this helped you, do these 3 things:\n"
                f"1. SUBSCRIBE and turn on ALL notifications\n"
                f"2. COMMENT your biggest takeaway below\n"
                f"3. SHARE with someone who needs to hear this\n\n"
                f"We post 4 videos EVERY DAY — shorts + deep dives.\n"
                f"New here? Start with our most popular videos on the channel page.\n\n"
                f"RELATED TOPICS: {kw_line}, personal finance for beginners, "
                f"how to invest money, budgeting tips, wealth building strategies, "
                f"financial literacy 2026, money management, passive income ideas\n\n"
                f"Subscribe: https://www.youtube.com/@TheAIDollar?sub_confirmation=1\n\n"
                f"#Finance #Money #PersonalFinance #Investing #WealthBuilding "
                f"#FinancialFreedom #MoneyTips #FinancialLiteracy "
                f"#HowToGetRich #StockMarket #PassiveIncome #DebtFree "
                f"#InvestingForBeginners #TheAIDollar "
                f"#MillionaireMindset #FinancialEducation "
                f"#MoneyMindset #WealthSecrets"
            )

        print(f"[TAGS] {len(yt_tags)} tags, {len(','.join(yt_tags))} chars: {yt_tags}")

        def _upload(tags):
            body = {
                "snippet": {
                    "title": yt_title,
                    "description": yt_desc,
                    "tags": tags,
                    "categoryId": "22",
                },
                "status": {
                    "privacyStatus": "public",
                    "selfDeclaredMadeForKids": False,
                },
            }
            media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
            request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    print(f"[UPLOAD] YouTube: {int(status.progress() * 100)}% uploaded")
            return response

        try:
            response = _upload(yt_tags)
        except HttpError as e:
            if "invalidTags" in str(e) or "invalid video keywords" in str(e):
                print(f"[WARN] Tags rejected ({e}), retrying with minimal safe tags...")
                safe_tags = ["personal finance", "money tips", "investing", "financial education", "TheAIDollar"]
                try:
                    response = _upload(safe_tags)
                except HttpError as e2:
                    print(f"[WARN] Minimal tags also rejected ({e2}), retrying with no tags...")
                    response = _upload([])
            else:
                raise

        video_id = response.get("id", "")
        print(f"[OK] YouTube uploaded! https://youtube.com/watch?v={video_id}")

        if thumbnail_path and os.path.exists(thumbnail_path) and video_id:
            try:
                youtube.thumbnails().set(
                    videoId=video_id,
                    media_body=MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
                ).execute()
                print(f"[OK] Custom thumbnail set for {video_id}")
            except Exception as te:
                print(f"[WARN] Thumbnail upload failed (requires verified channel): {te}")

        return True

    except Exception as e:
        try:
            _LAST_RUN["youtube_error"] = str(e)[:250]
        except Exception:
            pass
        print(f"[ERR] YouTube error: {e}")
        import traceback
        traceback.print_exc()
        return False


PUBLIC_BASE_URL = "https://the-ai-dollar.onrender.com"


def upload_to_instagram(video_path, title, keywords=None):
    """Post to Instagram via a Make.com scenario instead of talking to Meta
    directly — Make.com already has verified Meta API access, so this
    sidesteps Meta Developer Portal's SMS verification step entirely.
    Sends a webhook with a public URL to the video (Make's Instagram
    module fetches it from there) plus the caption."""
    # Instagram-only hold: set INSTAGRAM_RESUME_DATE=YYYY-MM-DD on Render and
    # Instagram won't post until that date (YouTube/TikTok keep posting).
    # Used to pause IG after an accidental over-post burst without stopping
    # the other platforms. Remove the var to run normally.
    resume = os.getenv("INSTAGRAM_RESUME_DATE", "").strip()
    if resume:
        try:
            resume_date = datetime.strptime(resume, "%Y-%m-%d").date()
            today = datetime.now().date()
            if today < resume_date:
                print(f"[SKIP] Instagram: on hold until {resume} (server date is {today})")
                return False
        except ValueError:
            print(f"[WARN] INSTAGRAM_RESUME_DATE='{resume}' is not YYYY-MM-DD — ignoring")

    webhook_url = os.getenv("MAKE_INSTAGRAM_WEBHOOK_URL", "")
    if not webhook_url:
        print("[SKIP] Instagram: MAKE_INSTAGRAM_WEBHOOK_URL not set")
        return False

    try:
        # Instagram now reads the CAPTION TEXT itself as keywords for search
        # and recommendations — captions outrank hashtags for discovery — so
        # the opening lines spell the topic out in natural language rather
        # than relying on tags. Hashtags are capped at 5 (Instagram's current
        # limit) and kept niche: broad tags like #Finance bury a small
        # account and add little ranking value now.
        # NOTE: 5 is a HARD platform cap (rolled out Dec 2025) — Instagram
        # strips extra tags or rejects the post, so this must not be raised
        # even though YouTube now carries 7. Same vetting as YouTube: broad
        # tags (#finance, #money) and off-intent ones (#makemoneyonline,
        # #passiveincome, #sidehustles) are deliberately excluded.
        import re as _re
        kw_list = [k for k in (keywords or []) if k and len(k) <= 30][:2]
        kw_tags = [f"#{_re.sub(r'[^A-Za-z0-9]', '', k)}" for k in kw_list]
        niche_tags = ["#PersonalFinance", "#FinancialLiteracy",
                      "#MoneyTips", "#FinanceForBeginners"]
        tags = (kw_tags + [t for t in niche_tags if t.lower() not in
                           [x.lower() for x in kw_tags]])[:5]

        # Reach to non-followers is driven mostly by SAVES and COMMENTS, so
        # the caption asks a one-word question and prompts a save.
        comment_bait = [
            "Which one always confused you? 👇",
            "Did you know the difference? Comment yes or no 👇",
            "Be honest — did you mix these up? 👇",
            "Which one did you get wrong? Tell me below 👇",
        ]
        topic_line = ", ".join(kw_list) if kw_list else "personal finance basics"
        caption = (
            f"{title}\n\n"
            f"{topic_line} explained simply — what each one actually means, "
            f"how to tell them apart in seconds, and what confusing them "
            f"costs you in real money.\n\n"
            f"{random.choice(comment_bait)}\n\n"
            f"💾 Save this so you don't forget it.\n"
            f"➕ Follow @theaidollar — one money term explained simply, every day.\n\n"
            + " ".join(tags)
        )

        video_url = f"{PUBLIC_BASE_URL}/media/{os.path.basename(video_path)}"
        print(f"[Instagram] Notifying Make.com: {video_url}")

        resp = requests.post(
            webhook_url,
            json={"video_url": video_url, "caption": caption, "title": title},
            timeout=20,
        )
        if resp.status_code not in (200, 201, 202):
            print(f"[ERR] Instagram webhook failed: {resp.status_code} - {resp.text[:200]}")
            return False

        print("[OK] Instagram: sent to Make.com for posting")
        return True

    except Exception as e:
        print(f"[ERR] Instagram error: {e}")
        return False


def upload_to_facebook(video_path, title, keywords=None):
    """Upload video to Facebook Page as Reel"""
    page_token = os.getenv("FACEBOOK_PAGE_TOKEN", "")
    page_id = os.getenv("FACEBOOK_PAGE_ID", "")
    if not page_token or not page_id:
        print("[SKIP] Facebook: FACEBOOK_PAGE_TOKEN or FACEBOOK_PAGE_ID not set")
        return False

    try:
        kw_tags = " ".join(f"#{k.replace(' ', '')}" for k in (keywords or [])[:5])
        description = (
            f"{title}\n\n"
            f"Like + Follow The AI Dollar for daily money education.\n"
            f"New shorts and deep dives every day.\n\n"
            f"#Finance #Money #PersonalFinance #Investing "
            f"#FinanceTips #WealthBuilding #FinancialLiteracy "
            f"#MoneyHacks #FinancialFreedom #DebtFree "
            f"#InvestingForBeginners #MoneyTips {kw_tags}"
        )

        print("[UPLOAD] Facebook: uploading reel...")
        init_url = f"https://graph.facebook.com/v18.0/{page_id}/video_reels"
        init_resp = requests.post(init_url, data={
            "upload_phase": "start",
            "access_token": page_token,
        })
        if init_resp.status_code != 200:
            print(f"[ERR] Facebook init failed: {init_resp.text}")
            return False

        video_id = init_resp.json().get("video_id")

        upload_url = f"https://rupload.facebook.com/video-upload/v18.0/{video_id}"
        file_size = os.path.getsize(video_path)
        with open(video_path, "rb") as f:
            upload_resp = requests.post(upload_url, data=f, headers={
                "Authorization": f"OAuth {page_token}",
                "offset": "0",
                "file_size": str(file_size),
                "Content-Type": "application/octet-stream",
            })
        if upload_resp.status_code != 200:
            print(f"[ERR] Facebook upload failed: {upload_resp.text}")
            return False

        publish_resp = requests.post(init_url, data={
            "upload_phase": "finish",
            "access_token": page_token,
            "video_id": video_id,
            "title": title[:100],
            "description": description,
        })
        if publish_resp.status_code == 200:
            print(f"[OK] Facebook Reel posted! Video ID: {video_id}")
            return True
        else:
            print(f"[ERR] Facebook publish failed: {publish_resp.text}")
            return False

    except Exception as e:
        print(f"[ERR] Facebook error: {e}")
        return False


_LAST_RUN = {"stage": "idle", "at": "", "title": "", "youtube": None, "tiktok": None, "instagram": None, "youtube_error": ""}


def _mark(stage, title=""):
    """Record the current post stage so /status can show where a run is (or
    where it got stuck) without needing access to Render's logs."""
    _LAST_RUN["stage"] = stage
    _LAST_RUN["at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    if title:
        _LAST_RUN["title"] = title
    print(f"[STAGE] {stage} {title}")


def post_video(is_series_part=False, series_name="", part_num=0, post_instagram=True,
               post_youtube=True, force=False):
    """Generate and post video to YouTube + TikTok (+ Instagram when
    post_instagram=True). Instagram Reels reach is hurt by over-posting —
    Meta's own creator guidance caps effective frequency around 1-2/day,
    unlike YouTube Shorts/TikTok which reward higher volume — so only a
    couple of the day's scheduled slots pass post_instagram=True."""
    # Global kill-switch: set PAUSE_POSTING=true on Render to deploy/run the
    # latest code WITHOUT posting anywhere (startup post and scheduled posts
    # both become no-ops). Remove it (or set false) to go live again.
    # force=True (from /post-now) bypasses the pause for a manual test.
    if not force and os.getenv("PAUSE_POSTING", "false").lower() == "true":
        print("[PAUSED] PAUSE_POSTING is set — skipping this post (nothing sent to YouTube/TikTok/Instagram).")
        return

    print(f"\n{'='*50}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] POSTING VIDEO{' [SERIES PART]' if is_series_part else ''}")
    print(f"{'='*50}\n")

    try:
        _mark("generating_video")
        print("[STEP 1] Generating video...")
        result = generate_daily_video()

        if result['status'] != 'success':
            _mark("ERROR_video_generation", str(result.get('message', ''))[:80])
            print(f"[ERR] Video generation failed: {result.get('message','')}")
            return

        video_path = result['video']
        title      = result['title']
        script     = result['script']
        keywords   = result.get('keywords', [])
        _mark("video_ready", title[:60])
        print(f"[OK] Video generated: {title}")

        if post_youtube:
            print(f"\n[STEP 2] Uploading to YouTube...")
            _mark("uploading_youtube", title[:60])
            youtube_success = upload_to_youtube(video_path, title, script, is_short=True, keywords=keywords)
            _LAST_RUN["youtube"] = bool(youtube_success)
        else:
            print(f"\n[STEP 2] Skipping YouTube this slot (1 upload/day)")
            youtube_success = None
            _LAST_RUN["youtube"] = "skipped"

        # TikTok is off until the app clears review. Without approval the
        # Content Posting API can only publish as SELF_ONLY (private), which
        # does nothing for growth and just burns build time. Gated on the
        # same TIKTOK_AUDITED flag that unlocks public posting, so it
        # resumes automatically the moment that's set.
        if os.getenv("TIKTOK_AUDITED", "false").lower() == "true":
            print(f"\n[STEP 3] Uploading to TikTok...")
            _mark("uploading_tiktok")
            tiktok_success = upload_to_tiktok(video_path, title, keywords=keywords)
            _LAST_RUN["tiktok"] = bool(tiktok_success)
        else:
            print(f"\n[STEP 3] Skipping TikTok (unapproved app posts privately only)")
            tiktok_success = None
            _LAST_RUN["tiktok"] = "skipped"

        if post_instagram:
            print(f"\n[STEP 4] Uploading to Instagram...")
            _mark("uploading_instagram")
            instagram_success = upload_to_instagram(video_path, title, keywords=keywords)
            _LAST_RUN["instagram"] = bool(instagram_success)
        else:
            print(f"\n[STEP 4] Skipping Instagram this slot (throttled to ~2 posts/day for reach)")
            instagram_success = None
            _LAST_RUN["instagram"] = "skipped"

        _mark("complete", title[:60])
        with open("last_post_time.txt", "w") as f:
            f.write(str(time.time()))

        print(f"\n{'='*50}")
        print(f"[DONE] POSTING COMPLETE")
        yt_status = "skipped (1/day)" if youtube_success is None else ("posted" if youtube_success else "FAILED")
        print(f"   YouTube:   {yt_status}")
        tt_status = "skipped (not approved)" if tiktok_success is None else ("posted" if tiktok_success else "FAILED")
        print(f"   TikTok:    {tt_status}")
        ig_status = "skipped (throttled)" if instagram_success is None else ("posted" if instagram_success else "FAILED")
        print(f"   Instagram: {ig_status}")
        print(f"{'='*50}\n")

    except Exception as e:
        _mark("ERROR_exception", str(e)[:120])
        print(f"[ERR] Error in post_video: {e}")
        import traceback
        traceback.print_exc()


def post_long_video():
    """Generate and post a long-form video to YouTube + TikTok"""
    print(f"\n{'='*50}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] POSTING LONG-FORM VIDEO")
    print(f"{'='*50}\n")

    try:
        print("[STEP 1] Generating long-form video...")
        result = generate_long_video()

        if result['status'] != 'success':
            print(f"[ERR] Long video generation failed: {result.get('message','')}")
            return

        video_path = result['video']
        title      = result['title']
        script     = result['script']
        keywords   = result.get('keywords', [])
        thumb      = result.get('thumbnail')
        print(f"[OK] Long video generated: {title}")

        print(f"\n[STEP 2] Uploading to YouTube (long-form)...")
        youtube_success = upload_to_youtube(video_path, title, script, is_short=False, keywords=keywords, thumbnail_path=thumb)

        print(f"\n[STEP 3] Uploading to TikTok...")
        tiktok_success = upload_to_tiktok(video_path, title, keywords=keywords)

        with open("last_post_time.txt", "w") as f:
            f.write(str(time.time()))

        print(f"\n{'='*50}")
        print(f"[DONE] LONG-FORM POSTING COMPLETE")
        print(f"   YouTube:   {'posted' if youtube_success else 'FAILED'}")
        print(f"   TikTok:    {'posted' if tiktok_success else 'FAILED'}")
        print(f"{'='*50}\n")

    except Exception as e:
        print(f"[ERR] Error in post_long_video: {e}")
        import traceback
        traceback.print_exc()


def keep_alive():
    """Self-ping to prevent Render free tier from spinning down"""
    try:
        requests.get("https://the-ai-dollar.onrender.com/", timeout=10)
    except Exception:
        pass


def upload_to_tiktok(video_path, title, keywords=None):
    """Upload video to TikTok using the official Content Posting API."""
    client_key = os.getenv("TIKTOK_CLIENT_KEY", "").strip()
    client_secret = os.getenv("TIKTOK_CLIENT_SECRET", "").strip()
    refresh_token = os.getenv("TIKTOK_REFRESH_TOKEN", "").strip()

    if not client_key or not client_secret or not refresh_token:
        print("[SKIP] TikTok: TIKTOK_CLIENT_KEY/CLIENT_SECRET/REFRESH_TOKEN not fully set")
        return False

    print(f"[TikTok] client_key len={len(client_key)} repr={client_key[:4]!r}...{client_key[-4:]!r}")
    print(f"[TikTok] client_secret len={len(client_secret)}")
    print(f"[TikTok] refresh_token len={len(refresh_token)} repr={refresh_token[:8]!r}...{refresh_token[-8:]!r}")

    try:
        import requests as req

        kw_tags = " ".join(f"#{k.replace(' ', '')}" for k in (keywords or [])[:3])
        caption = (
            f"{title[:60]} "
            f"#moneytok #fintok #investing #finance #personalfinance "
            f"#moneytips #financialfreedom #wealthbuilding "
            f"#learnontiktok #fyp #viral {kw_tags}"
        )[:150]

        print("[TikTok] Refreshing access token...")
        token_resp = req.post(
            "https://open.tiktokapis.com/v2/oauth/token/",
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            data={
                "client_key": client_key,
                "client_secret": client_secret,
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            },
            timeout=20,
        )
        token_data = token_resp.json()
        access_token = token_data.get("access_token")
        if not access_token:
            print(f"[ERR] TikTok token refresh failed: {token_data}")
            return False

        auth_headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json; charset=UTF-8",
        }

        print("[TikTok] Querying creator info...")
        creator_resp = req.post(
            "https://open.tiktokapis.com/v2/post/publish/creator_info/query/",
            headers=auth_headers,
            timeout=20,
        )
        creator_data = creator_resp.json().get("data", {})
        privacy_options = creator_data.get("privacy_level_options", ["SELF_ONLY"])

        # Unaudited apps can ONLY post as SELF_ONLY, even if PUBLIC_TO_EVERYONE
        # is listed as an option — TikTok's posting endpoint enforces this
        # separately from what creator_info reports. Flip TIKTOK_AUDITED=true
        # on Render once the app passes review to allow public posting.
        if os.getenv("TIKTOK_AUDITED", "false").lower() == "true" and "PUBLIC_TO_EVERYONE" in privacy_options:
            privacy_level = "PUBLIC_TO_EVERYONE"
        else:
            privacy_level = "SELF_ONLY"
        print(f"[TikTok] Privacy level: {privacy_level}")

        file_size = os.path.getsize(video_path)
        print(f"[TikTok] Video size: {file_size / 1024 / 1024:.1f}MB")

        print("[TikTok] Initializing post...")
        init_resp = req.post(
            "https://open.tiktokapis.com/v2/post/publish/video/init/",
            headers=auth_headers,
            json={
                "post_info": {
                    "title": caption,
                    "privacy_level": privacy_level,
                    "disable_duet": False,
                    "disable_comment": False,
                    "disable_stitch": False,
                    "video_cover_timestamp_ms": 1000,
                },
                "source_info": {
                    "source": "FILE_UPLOAD",
                    "video_size": file_size,
                    "chunk_size": file_size,
                    "total_chunk_count": 1,
                },
            },
            timeout=20,
        )
        init_data = init_resp.json()
        if "data" not in init_data or "publish_id" not in init_data["data"]:
            print(f"[ERR] TikTok init failed: {init_data}")
            return False

        publish_id = init_data["data"]["publish_id"]
        upload_url = init_data["data"]["upload_url"]

        print("[TikTok] Uploading video...")
        with open(video_path, 'rb') as f:
            video_data = f.read()

        upload_resp = req.put(
            upload_url,
            headers={
                "Content-Type": "video/mp4",
                "Content-Range": f"bytes 0-{file_size - 1}/{file_size}",
            },
            data=video_data,
            timeout=120,
        )
        print(f"[TikTok] Upload response: {upload_resp.status_code}")
        if upload_resp.status_code not in (200, 201):
            print(f"[ERR] TikTok upload failed: {upload_resp.status_code} - {upload_resp.text[:200]}")
            return False

        print("[TikTok] Checking publish status...")
        for _ in range(6):
            time.sleep(5)
            status_resp = req.post(
                "https://open.tiktokapis.com/v2/post/publish/status/fetch/",
                headers=auth_headers,
                json={"publish_id": publish_id},
                timeout=20,
            )
            status_data = status_resp.json().get("data", {})
            status = status_data.get("status")
            print(f"[TikTok] Status: {status}")
            if status == "PUBLISH_COMPLETE":
                print(f"[OK] TikTok posted! Title: {title[:50]}")
                return True
            if status == "FAILED":
                print(f"[ERR] TikTok publish failed: {status_data}")
                return False

        print("[WARN] TikTok publish status unknown after polling, treating as posted")
        return True

    except Exception as e:
        print(f"[ERR] TikTok error: {e}")
        return False


def _post_async(post_instagram=True, post_youtube=True):
    """Kick off a post in a BACKGROUND thread so the scheduler loop and the
    keep-alive self-ping keep running. A video build takes several minutes;
    if it ran on the main/scheduler thread it would block the 10-min self-ping,
    Render would see no traffic, spin the instance down mid-build, and nothing
    would ever finish posting (root cause of 'last_post: never')."""
    threading.Thread(
        target=lambda: post_video(post_instagram=post_instagram,
                                  post_youtube=post_youtube),
        daemon=True,
    ).start()


def schedule_jobs():
    # Times are UTC; US East is UTC-4 (EDT). Slots sit inside the two windows
    # that 2026 Shorts timing studies agree on — roughly 11am-2pm and 6-9pm
    # ET — with the YouTube slot placed at 4pm ET, the single best-performing
    # hour in Buffer's analysis.
    #
    # YouTube is capped at ONE upload per day and takes the strongest slot;
    # posting the same channel 3x daily splits its own audience across
    # uploads instead of concentrating first-hour velocity on one video.
    # TikTok keeps all 3 (it rewards volume); Instagram keeps 2 (its reach
    # degrades with more, and 5 hashtags/2 posts is the safe ceiling).
    #
    # The 20:00 slot posts to YouTube AND Instagram, so the day's strongest
    # video goes out on both. Splitting them onto separate slots meant the
    # two platforms never carried the same video at all.
    # With TikTok gated off, a slot that posts to neither YouTube nor
    # Instagram would build a video and then discard it, so the old
    # third (TikTok-only) slot is gone.
    schedule.every().day.at("15:30").do(                        # 11:30am ET — Instagram
        _post_async, post_instagram=True, post_youtube=False)
    schedule.every().day.at("20:00").do(                        # 4:00pm ET — best hour: YT + IG
        _post_async, post_instagram=True, post_youtube=True)

    schedule.every(10).minutes.do(keep_alive)
    print("[OK] Schedule: 1/day YouTube (20:00 UTC) + 2/day Instagram (15:30, 20:00). TikTok off.")
    print("[OK] Shorts = discovery engine for non-subscribers")
    print("[OK] Self-ping every 10 min to prevent Render spin-down")


def main():
    print("\n[START] THE AI DOLLAR - AUTOMATION STARTED")
    print("=" * 50)
    print(f"Started at: {datetime.now()}")
    print("=" * 50)

    health_thread = threading.Thread(target=start_health_server, daemon=True)
    health_thread.start()

    schedule_jobs()

    # No startup post. It used to exist so a redeploy proved the pipeline
    # end to end, but with TikTok gated off it would post to nothing —
    # YouTube's single daily upload is reserved for the 20:00 slot and
    # Instagram is capped at its two scheduled slots. Everything now runs
    # purely on the schedule; use /post-now to trigger one on demand.
    print("\n[NOW] Startup post disabled — posting runs on schedule only.\n")

    print("\n[SCHED] Scheduler running (1/day YouTube, 2/day Instagram + self-ping every 10 min)...")
    try:
        while True:
            schedule.run_pending()
            time.sleep(30)
    except KeyboardInterrupt:
        print("\n[STOP] Stopped")


if __name__ == "__main__":
    main()
